### ISSUE TITLE
docker-build.sh ../dist directory missing

### ISSUE THREAD

**Issue by misilot** [zemkat/grima#5]
When running docker-build.sh the ../dist directory is missing.

**Comment by zemkat** [comment]
This is only needed if you are developing your own grimas, and want to publish docker images for other people to use. The script may have accidentally been included in the release, but should only really be in the github source code. The dist directory and its contents are created using the "make" command, which builds all of the documentation as well. You should not need to run this. Sorry for any confusion!

**Comment by misilot** [comment]
Sorry, I was looking at the source code and not the releases. Right now I think we will be working with the already built grimas.

**Comment by misilot** [comment]
@zemkat we are starting to look at building our own Grima's and if we wanted to share the image with others here. Are there detailed directions on how to get custom grima's to show up using a released version instead of building my own. Thanks!

**Comment by misilot** [comment]
When trying to run make jekyll, I get the following error 

```node fix_urls.js
/home/user/grima/fix_urls.js:48
    if (dirEnt.isDirectory()) {
               ^

TypeError: dirEnt.isDirectory is not a function
    at recurse (/home/user/grima/fix_urls.js:48:16)
    at Object.<anonymous> (/home/user/grima/fix_urls.js:61:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by jackschmidt** [comment]
The `fix_urls.js` problem is fixed in 6fcc076dc1964cf2b1d35115475fa6cd98aaa138

I think the current advice is end-users should use a docker image. In the next week or so, the docker image and script will be updated to be a bit easier to use.

Developers should hopefully just be able to run the php directly (the dist/ directory turns markdown and code comments into html, but has no effect on the pure functionality).

To send those grimas to end-users (if you aren't just running an apache+php webserver with two directories for grima: dev and release) the next release should have build scripts for the docker image, and a better `grima.bat` script for end-users that will auto-update.

If you use the released grima on a webserver, you can just put your own `grimas/YourGrima/YourGrima.php` etc. in the directory. If your users go through the docker image on Windows, then it seems difficult to do smoothly. You can edit `grima.bat` to add some `-v LocalDir:/home/grima/grimas/YourGrima` options to docker, but it would be one option per grima, and no easy way to edit the grima-lib.

Let us know if you have found a nice way (or have ideas) to include the grimas easily.

**Comment by misilot** [comment]
@zemkat just curious what versions of Node and Ruby you are using? I am working on trying to get this to build locally, it is failing on node fix_urls.js.

Thank you!
